### ISSUE TITLE
Hello Skadewdle

### ISSUE THREAD

**Issue by aadhar54** [skadewdle/mulyankan#2]
I want to build something amazing like this .Can you help me understand the process .I am really inspired by mulyankan .Its awesome .Kindly write a blog or shoot a 5-10 min youtube video guiding  people like me (fan of your work) .Its a request from an admirer!

**Comment by skadewdle** [comment]
Yes. I am planning on doing that very soon. It will be up on my new Youtube channel very soon. I'll notify you when I upload it. And thanks a lot for your kind words 🙂️
